### Register
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

###w

### Login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Request Challenge
POST {{host}}/auth/request-challenge
Content-type: application/json

{
  "email": "{{email}}",
  "address": "Oxfacu"
}