### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

### Get me
GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}