### GET STRATEGIES
GET {{host}}/investment/strategies
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE INVESTMENT PROPOSAL
POST {{host}}/investment/proposal/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": "100",
  "strategy_id": "2a38acb1-d9fe-42f0-aad5-10226d06f752",
  "currency_id": "33de6c7c-62a2-4182-813a-9005183be70d"
}

### EXECUTE INVESTMENT PROPOSAL
POST {{host}}/investment/execute/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "proposal_id": "34bf387f-a41a-4283-ad15-509bd80e570d"
}

### GET INVESTMENTS
GET {{host}}/investment/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### WITHDRAW INVESTMENT
POST {{host}}/investment/withdraw/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "investment_id": "7d6c44fa-b8b8-4d09-a03b-1b31664ef8ff"
}
