### GET STRATEGIES
GET {{host}}/investment/strategies
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE INVESTMENT PROPOSAL
POST {{host}}/investment/proposal/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": "100",
  "strategy_id": "5f267d25-4370-4402-9f1d-93695147e484",
  "currency_id": "33de6c7c-62a2-4182-813a-9005183be70d"
}

### EXECUTE INVESTMENT PROPOSAL
POST {{host}}/investment/execute/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "proposal_id": "cdd85569-08f7-4726-9890-cd8023444982"
}

### GET INVESTMENTS
GET {{host}}/investment/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### WITHDRAW INVESTMENT
POST {{host}}/investment/withdraw/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "investment_id": "f2ce796b-0212-4cfe-a911-394a17020096"
}
