name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.32.1
          run_install: false

      - name: Install
        working-directory: client
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: client
        env:
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
          PUBLIC_VAULT_CONTRACT_ADDRESS: ${{ secrets.PUBLIC_VAULT_CONTRACT_ADDRESS }}
          VITE_PUBLIC_REOWN_KEY: ${{ secrets.VITE_PUBLIC_REOWN_KEY }}
          VITE_PUBLIC_RPC_URL: ${{ secrets.VITE_PUBLIC_RPC_URL }}
        run: pnpm build

      - name: Verify output
        working-directory: client
        run: |
          echo "=== BUILD ==="
          find build -maxdepth 3 -type f | sort

          echo
          echo "=== STATIC ==="
          ls -lah build/static

          echo
          echo "=== SERVER ==="
          ls -lah build/server

          echo
          echo "=== CONFIG ==="
          ls -lah build/staticwebapp.config.json

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BEACH_095F29C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          action: upload

          app_location: client
          api_location: client/build/server
          output_location: build/static

          skip_app_build: true

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    runs-on: ubuntu-latest

    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BEACH_095F29C0F }}